### ISSUE TITLE
is there current a sense to have it ?

### ISSUE THREAD

**Issue by hannesa2** [originx/android_emulator_docker#14]
https://github.com/originx/android_emulator_docker/blob/63240f881c7955c59deedc2a1c825bf2cac34f46/Dockerfile#L53

**Comment by hannesa2** [comment]
we use it

**Comment by originx** [comment]
E. G.
docker-compose up - - build-args emu=27,x86

Or we can keep it simple like it is now, lets see what use case pops up when we start using it on CI
