### ISSUE TITLE
apply proxysettings

### ISSUE THREAD

**Issue by hannesa2** [originx/android_emulator_docker#6]
https://github.com/originx/android_emulator_docker/blob/538d504d1f0e135ec440980095e1384e93382876/Dockerfile#L38

can I run here any shell command ?

**Comment by originx** [comment]
yes, this is pure shell after RUN

**Comment by hannesa2** [comment]
extract values is not an issue.
But in DockerFile you don't see variables form host, so you have to set it.
(Or I at least was not able to see it)

ENV PROXY_PROTOCOL http
ENV PROXY_SERVER example.com
ENV PROXY_PORT 8080
RUN yes | sdkmanager --update --verbose --proxy_host=$PROXY_SERVER --proxy_port=$PROXY_PORT --proxy_protocol=$PROXY_PROTOCOL

currently I play arround how to set it from outside ...

**Comment by originx** [comment]
there are many ways to set it, here isa good blog if you want to see:
https://vsupalov.com/docker-arg-env-variable-guide/

I opened a bug for google sdkmanager which will help us clean it more later:
https://issuetracker.google.com/issues/79122663

**Comment by hannesa2** [comment]
I'm close to a solution. We have to use ARG. This works.
But now I try to read from `.env`file or `.env_file` but they are good for ENV, not for ARG.

Yes, everyone runs into https://vsupalov.com/docker-arg-env-variable-guide/ ;-)

**Comment by hannesa2** [comment]
I will make WIP PR and probably continue tomorrow

**Comment by originx** [comment]
solved with #15
