### ISSUE TITLE
generell proxy setting

### ISSUE THREAD

**Issue by hannesa2** [originx/android_emulator_docker#7]
The first steps are not perfect, concerning several issues
A:
`docker-compose up` 
and 
B:
`docker build -t hannes_tag_emulator . --build-arg HTTP_PROXY=http://muc-web-01.server.com:8080 --build-arg HTTPS_PROXY=https://muc-web-01.server.com:8080`

btw `server.com` is a synonym 

stops here, because of proxy issue (I'm in VPN)

> Step 8/29 : RUN   apt-get update &&   apt-get install -y openjdk-8-jdk
>  ---> Running in 426ce5c56561

I'm running our squid . 
And I recommend using our setupProxy.sh script to have everywhere same condition/pain on every machine. -> **solving once, solving everywhere !**

**Comment by originx** [comment]
still open until we remember to add our CI and machine proxy too with setupProxy.sh script

**Comment by hannesa2** [comment]
how does your untouched `~/.docker/config.json` looks like ?
mine:

 ```
 "auths" : {

  }
}
```

**Comment by originx** [comment]
`on my mac its like this:

{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://hostname:3128",
     "httpsProxy": "http://hostname:3128"
   }
 }
}`

untouched I do not know, I think it was empty for me

**Comment by originx** [comment]
also tabs and indentations are very important I did not enter it correctly in the comment but you can see it here:
https://docs.docker.com/network/proxy/#configure-the-docker-client

**Comment by hannesa2** [comment]
do you checked if it works with `http://localhost:3128` ?

**Comment by originx** [comment]
for localhost it does not work, docker image tries to connect to itself then 127.0.0.1, you need to enter the hostname

**Comment by hannesa2** [comment]
Ok, PR on DSA need rework :-(
